(()=>{
window.breezBackgrounds={"product":"assets/036d585d9495f1.webp","premium":"assets/65bbb544359409.webp","short":"assets/5cc86b5c59d583.webp","feed":"assets/655dcc9d9d91e4.webp","story":"assets/6f133871c58f04.webp","banner":"assets/1dd72014537782.webp"};document.documentElement.style.setProperty("--breez-generated-product",`url("${window.breezBackgrounds.product}")`);
window.breezEdits={};window.breezEditors={};
window.breezEditSummary=key=>{let entry=window.breezEdits[key];return entry?entry.state.elements.map(e=>`${e.label}: 위치 ${Math.round(e.x)}, ${Math.round(e.y)} / 크기 ${Math.round(e.w)} × ${Math.round(e.h)}${e.text?' / 문구 '+e.text.replaceAll('\n',' '):''}`).join('\n'):'직접 편집 전';};
window.mountBreezEditor=function(root,src,config){
if(!root||root.dataset.ready)return;root.dataset.ready='1';
const key=`${config.mode}:${config.variant}:${config.priority||''}`;
root.innerHTML=`<div class="bz-toolbar"><button data-action="undo" aria-label="실행 취소">↶ 실행 취소</button><button data-action="redo" aria-label="다시 실행">↷</button><button data-action="reset">시안 초기화</button><button data-action="export">PNG 저장 ↓</button></div><div class="bz-stage"><canvas class="bz-canvas" tabindex="0" aria-label="광고 편집 영역. 요소를 선택하고 드래그하거나 방향키로 이동하세요."></canvas></div><p class="bz-hint"><span class="hint-group">배경·제품·문구를 선택해 드래그</span><span class="hint-group">모서리로 비율 유지 크기 조절</span><span class="hint-group">Shift + 클릭으로 여러 요소 선택</span><span class="hint-group">캔버스 밖은 자동으로 잘립니다</span></p><div class="bz-selection"><span class="bz-selected-name">배경·제품 또는 문구를 클릭하세요</span><button data-action="clear">선택 해제</button></div><div class="bz-properties"><label class="bz-text-label">문구 편집<textarea class="bz-text" rows="2" maxlength="100"></textarea></label><div class="bz-controls"><label>크기<input class="bz-size" type="range" aria-label="선택 요소 크기"></label><button data-action="center">중앙 정렬</button></div><details class="bz-more"><summary>추가 옵션</summary><label class="bz-color-label">글자 색상<input class="bz-color" type="color"></label><div class="bz-actions"><button data-action="left">왼쪽 정렬</button><button data-action="right">오른쪽 정렬</button><button data-action="middle">세로 중앙</button><button data-action="front">앞으로</button><button data-action="back">뒤로</button></div><p class="bz-dimensions"></p></details></div><details class="bz-recovery"><summary>화면 밖 요소 찾기 · 편집 설정</summary><label>요소 선택<select class="bz-select"><option value="">선택하세요</option></select></label><button data-action="recover">선택 요소 화면 중앙으로</button><label class="bz-snap-label"><input class="bz-snap" type="checkbox" checked> 중앙·끝선 자동 정렬</label><label class="bz-multi-label"><input class="bz-multi" type="checkbox"> 여러 요소 선택 (터치용)</label><label class="bz-motion-label"><input class="bz-motion" type="checkbox" checked> 마우스 반응 효과</label></details><p class="bz-status" role="status" aria-live="polite"></p>`;
const $=s=>root.querySelector(s),canvas=$('.bz-canvas'),ctx=canvas.getContext('2d'),pic=new Image(),bgpic=new Image(),clone=x=>JSON.parse(JSON.stringify(x));let state,baseline,selected=null,undo=[],redo=[],drag=null,raf=0,guides=[],crop={x:0,y:0,w:640,h:800},loaded=false;let motion={x:0,y:0};let selectedIds=new Set();const motionMedia=window.matchMedia?window.matchMedia('(prefers-reduced-motion: no-preference) and (hover: hover) and (pointer: fine)'):{matches:false};
const colors={ink:'#183b2c',paper:'#f3efe6',gold:'#e5d7b7',green:'#173d30'};
function text(id,label,x,y,content,size,color=colors.ink){return{id,label,x,y,text:content,size,color,w:1,h:1};}
function isLocked(e){return !!e&&!!e.locked;}
function background(x,y,w,h){return{id:'background',label:'배경',x,y,w,h,background:true};}
function ensureBackground(els,width=1080,height=1350){els=els||[];let bg=els.find(e=>e.id==='background');if(!bg){els.unshift(background(0,0,width,height));}else{bg.label='배경';bg.background=true;if(!Number.isFinite(bg.x))bg.x=0;if(!Number.isFinite(bg.y))bg.y=0;if(!Number.isFinite(bg.w)||bg.w<=0)bg.w=width;if(!Number.isFinite(bg.h)||bg.h<=0)bg.h=height;}return els;}
function cleanLegacyElements(els,variant,width=1080,height=1350){let hadLegacy=(els||[]).some(e=>e.id==='volume'||e.id==='price');let cta=(els||[]).find(e=>e.id==='cta');let hadFixedCta=!!cta&&(cta.locked||cta.fixed);els=(els||[]).filter(e=>e.id!=='volume'&&e.id!=='price');cta=els.find(e=>e.id==='cta');if(cta){delete cta.locked;delete cta.fixed;delete cta.panel;delete cta.panelText;delete cta.panelBorder;}els=ensureBackground(els,width,height);if((hadLegacy||hadFixedCta)&&cta)placeCta(els,variant);return els;}
function cleanLegacyHistory(items,variant,width=1080,height=1350){return(items||[]).map(entry=>{let copy=clone(entry);copy.elements=cleanLegacyElements(copy.elements,variant,copy.width||width,copy.height||height);return copy;});}
function overlaps(a,b){return !!a&&!!b&&a.x<b.x+b.w&&b.x<a.x+a.w&&a.y<b.y+b.h&&b.y<a.y+a.h;}
function placeCta(els,variant){let headline=els.find(e=>e.id==='headline'),cta=els.find(e=>e.id==='cta');if(!headline||!cta)return;measure(headline);measure(cta);if(variant==='banner'){cta.x=55;cta.y=150;return;}let gap=26;cta.y=headline.y+headline.h+gap;if(variant==='premium'||variant==='story')cta.center=true;else cta.x=headline.x;let support=els.find(e=>e.id==='support');if(support&&(variant==='before'||variant==='feed'))support.y=cta.y+cta.h+20;let productEl=els.find(e=>e.id==='product');if(productEl&&overlaps(productEl,cta))productEl.y=cta.y+cta.h+32;}
function product(x,y,h){return{id:'product',label:'제품',x,y,h,w:h*.32};}
function preset(){let v=config.variant,channel=config.mode==='channel',dark=v==='premium'||v==='story',c=dark?'#fff5e2':colors.ink,w=1080,h=channel?(v==='story'?1920:v==='banner'?360:1080):1350;
let els=[text('brand','브랜드',76,74,'BREEZ',42,c),text('name','제품명',78,133,'포레스트 룸 스프레이',23,dark?'#daceb6':'#617062'),text('headline','메인 문구',76,280,config.headline,82,c),product(675,340,690),{...text('cta','버튼',76,420,'제품 살펴보기  →',28,dark?'#173d30':'#fff9ed'),button:true,bg:dark?'#e5d7b7':'#234a36'}];
if(v==='before'){els[2].y=260;els[2].size=58;els.splice(3,0,text('support','설명',76,440,'은은한 향을 좋아하는 당신에게\n집 안의 분위기를 바꾸는 새로운 선택',27,'#65745f'));let p=els.find(x=>x.id==='product');p.x=435;p.y=610;p.h=420;}
if(v==='product'){els[2].size=94;els[2].y=320;let p=els.find(x=>x.id==='product');p.x=662;p.y=222;p.h=730;}
if(v==='premium'){els[0].center=true;els[0].y=78;els[1].center=true;els[1].y=143;els[2].center=true;els[2].size=62;els[2].y=210;let p=els.find(x=>x.id==='product');p.center=true;p.y=480;p.h=495;}
if(v==='short'){els[2].size=115;els[2].y=300;let p=els.find(x=>x.id==='product');p.x=690;p.y=180;p.h=800;}
if(v==='feed'){els[2].size=75;els[2].y=220;let p=els.find(x=>x.id==='product');p.x=752;p.y=120;p.h=620;els.splice(3,0,text('support','설명',78,495,'나만의 공간에 더하는\n은은한 향과 차분한 분위기',24,'#617062'));}
if(v==='story'){els[0].center=true;els[0].y=110;els[1].center=true;els[1].y=190;els[2].center=true;els[2].size=105;els[2].y=270;let p=els.find(x=>x.id==='product');p.center=true;p.y=770;p.h=620;}
if(v==='banner'){els=[text('brand','브랜드',55,38,'BREEZ',25),text('name','제품명',56,77,'포레스트 룸 스프레이',17,'#617062'),text('headline','메인 문구',735,92,config.headline,43),product(605,12,265),{...text('cta','버튼',55,178,'살펴보기 →',24,'#fff9ed'),button:true,bg:'#234a36'}];}
if(channel){let p=els.find(e=>e.id==='product'),headline=els.find(e=>e.id==='headline'),cta=els.find(e=>e.id==='cta');if(config.priority==='product'){p.h*=1.05;}if(config.priority==='message')headline.size*=1.12;if(config.priority==='cta'){cta.size*=1.15;cta.bg=dark?'#f5df99':'#123d29';}}
els.unshift(background(0,0,w,h));
placeCta(els,v);
return{width:w,height:h,variant:v,dark,bg:dark?'#173d30':v==='short'?'#dfebd4':'#f3efe6',elements:els};}
function font(e){return `${e.id==='headline'?(config.variant==='premium'?500:700):e.id==='brand'?600:500} ${e.size}px Pretendard, Arial, sans-serif`;}
function measure(e){if(e.id==='background')return;if(e.id==='product'){e.w=e.h*crop.w/crop.h;return;}ctx.font=font(e);const ls=e.text.split('\n');e.w=Math.max(28,...ls.map(l=>ctx.measureText(l).width))+12;e.h=e.size*1.24*ls.length+10;if(e.button){e.w+=52;e.h=e.size+40;}}
function fitAll(s){for(let e of s.elements){measure(e);if(e.center)e.x=(s.width-e.w)/2;if(e.right)e.x=s.width-76-e.w;delete e.center;delete e.right;fitToCanvas(e,s);}}
function fitToCanvas(e,s=state){if(!Number.isFinite(e.x))e.x=0;if(!Number.isFinite(e.y))e.y=0;}
function current(){let e=state.elements.find(e=>e.id===selected);return isLocked(e)?null:e;}
function active(){return state.elements.filter(e=>selectedIds.has(e.id)&&!isLocked(e));}
function selectOne(id){let e=state.elements.find(e=>e.id===id);if(isLocked(e))id=null;selected=id;selectedIds=new Set(id?[id]:[]);}
function bounds(){let a=active();if(!a.length)return null;let x=Math.min(...a.map(e=>e.x)),y=Math.min(...a.map(e=>e.y));return{x,y,w:Math.max(...a.map(e=>e.x+e.w))-x,h:Math.max(...a.map(e=>e.y+e.h))-y};}
function moveSelection(dx,dy){active().forEach(e=>{e.x+=dx;e.y+=dy;});}

function remember(){window.breezEdits[key]={state:clone(state),undo:clone(undo),redo:clone(redo)};if(typeof CustomEvent!=="undefined")window.dispatchEvent(new CustomEvent("breez-edit"));}
function save(){undo.push(clone(state));if(undo.length>60)undo.shift();redo=[];}
function commit(fn){save();fn();refresh();}
function backdrop(c,s,editing){let w=s.width,h=s.height;c.fillStyle=s.bg;c.fillRect(0,0,w,h);let bg=s.elements?.find(e=>e.id==='background');if(bgpic.complete&&(bgpic.naturalWidth||bgpic.width)){let frame=bg||{x:0,y:0,w,h},fw=Math.max(1,Number(frame.w)||w),fh=Math.max(1,Number(frame.h)||h),fx=Number(frame.x)||0,fy=Number(frame.y)||0,iw=bgpic.naturalWidth||bgpic.width,ih=bgpic.naturalHeight||bgpic.height,scale=Math.max(fw/iw,fh/ih)*1.035,dw=iw*scale,dh=ih*scale,mx=editing&&!selected?motion.x*8:0,my=editing&&!selected?motion.y*8:0;c.save();c.beginPath();c.rect(fx,fy,fw,fh);c.clip();c.drawImage(bgpic,fx+(fw-dw)/2+mx,fy+(fh-dh)/2+my,dw,dh);c.restore();}if(s.dark){const g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,'rgba(0,15,8,.22)');g.addColorStop(.45,'rgba(0,15,8,0)');g.addColorStop(1,'rgba(0,15,8,.18)');c.fillStyle=g;c.fillRect(0,0,w,h);}else{const g=c.createLinearGradient(0,0,w,0);g.addColorStop(0,'rgba(250,248,238,.14)');g.addColorStop(.65,'rgba(250,248,238,0)');c.fillStyle=g;c.fillRect(0,0,w,h);}}

function render(c,s,editing){backdrop(c,s,editing);for(const e of s.elements){if(e.id==='background')continue;c.save();if(editing&&!selected){let depth=e.id==='product'?10:3;c.translate(motion.x*depth,motion.y*depth);}if(e.id==='product'){if(loaded){c.shadowColor=s.dark?'#0005':'#243c2628';c.shadowBlur=22;c.shadowOffsetY=12;c.drawImage(pic,crop.x,crop.y,crop.w,crop.h,e.x,e.y,e.w,e.h);}}else{c.font=font(e);c.textBaseline='top';if(e.fixed&&!e.button){c.fillStyle=e.panel||(s.dark?'#f5e8cf':'#173d30');c.beginPath();c.roundRect(e.x,e.y,e.w,e.h,Math.max(7,e.size*.22));c.fill();c.strokeStyle=e.panelBorder||(s.dark?'#fff3d4':'#50785f');c.lineWidth=Math.max(1,e.size*.035);c.stroke();}if(e.button){c.fillStyle=e.bg||'#234a36';c.beginPath();c.roundRect(e.x,e.y,e.w,e.h,9);c.fill();if(e.fixed){c.strokeStyle=e.panelBorder||(s.dark?'#fff3d4':'#50785f');c.lineWidth=Math.max(1,e.size*.035);c.stroke();}c.fillStyle=e.color;c.fillText(e.text,e.x+32,e.y+20);}else{c.fillStyle=e.fixed?(e.panelText||e.color):e.color;e.text.split('\n').forEach((line,i)=>c.fillText(line,e.x+6,e.y+5+i*e.size*1.24));}}c.restore();}
if(editing&&current()){let e=bounds(),unit=s.width/Math.max(200,canvas.getBoundingClientRect().width),handle=9*unit;c.save();c.strokeStyle='#08b999';c.lineWidth=1.5*unit;if(active().length>1){c.save();c.globalAlpha=.55;c.setLineDash([5*unit,4*unit]);for(const part of active())c.strokeRect(part.x,part.y,part.w,part.h);c.restore();}c.strokeRect(e.x,e.y,e.w,e.h);c.fillStyle='#fff';for(const p of corners(e)){c.fillRect(p.x-handle/2,p.y-handle/2,handle,handle);c.strokeRect(p.x-handle/2,p.y-handle/2,handle,handle);}c.restore();}
if(editing){c.strokeStyle='#08b999';c.lineWidth=2;for(const g of guides){c.beginPath();g.axis==='x'?(c.moveTo(g.v,0),c.lineTo(g.v,s.height)):(c.moveTo(0,g.v),c.lineTo(s.width,g.v));c.stroke();}}}
function paint(){cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{if(root.isConnected!==false)render(ctx,state,true);});}
function refresh(){canvas.width=state.width;canvas.height=state.height;canvas.style.aspectRatio=`${state.width}/${state.height}`;root.dataset.variant=config.variant;$('.bz-stage').style.maxWidth=config.variant==='story'?'370px':'100%';$('[data-action="undo"]').disabled=!undo.length;$('[data-action="redo"]').disabled=!redo.length;$('.bz-select').replaceChildren(...[{id:'',label:'선택하세요'},...state.elements].map(e=>{let opt=document.createElement('option');opt.value=e.id;opt.textContent=(isLocked(e)?'🔒 ':'')+e.label;opt.disabled=isLocked(e);return opt;}));$('.bz-select').value=selected||'';$('.bz-selected-name').textContent=active().length>1?`${active().length}개 요소 함께 편집`:current()?current().label+' 편집':'배경·제품 또는 문구를 클릭하세요';$('[data-action="clear"]').hidden=!selected;let e=current();$('.bz-properties').hidden=!e;if(e){$('.bz-text').value=e.text||'';$('.bz-text-label').hidden=e.id==='product'||e.id==='background'||active().length>1;$('.bz-size').parentElement.hidden=active().length>1;$('.bz-color-label').hidden=active().every(x=>x.id==='product'||x.id==='background');$('.bz-color').value=e.color||'#183b2c';$('.bz-size').min=e.id==='product'?60:e.id==='background'?80:14;$('.bz-size').max=e.id==='product'?state.height*3:e.id==='background'?state.height*3:360;$('.bz-size').value=e.id==='product'||e.id==='background'?e.h:e.size;$('.bz-dimensions').textContent=`${e.label} · ${Math.round(e.w)} × ${Math.round(e.h)}px · 위치 ${Math.round(e.x)}, ${Math.round(e.y)}`;}remember();paint();}
function corners(e){return[{x:e.x,y:e.y,id:'nw'},{x:e.x+e.w,y:e.y,id:'ne'},{x:e.x,y:e.y+e.h,id:'sw'},{x:e.x+e.w,y:e.y+e.h,id:'se'}];}
function point(ev){let r=canvas.getBoundingClientRect();return{x:(ev.clientX-r.left)*state.width/r.width,y:(ev.clientY-r.top)*state.height/r.height};}
function handleAt(p,e){if(!e)return null;let radius=12*state.width/canvas.getBoundingClientRect().width;return corners(e).find(c=>Math.abs(c.x-p.x)<radius&&Math.abs(c.y-p.y)<radius);}
function hit(p){return [...state.elements].reverse().find(e=>!isLocked(e)&&(()=>{let depth=e.id==='background'?0:e.id==='product'?10:3,dx=selected||e.id==='background'?0:motion.x*depth,dy=selected||e.id==='background'?0:motion.y*depth;return p.x>=e.x+dx&&p.x<=e.x+e.w+dx&&p.y>=e.y+dy&&p.y<=e.y+e.h+dy;})());}
function resetMotion(){motion={x:0,y:0};$('.bz-stage').style.transform='none';paint();}
$('.bz-select').addEventListener('change',ev=>{selectOne(ev.target.value||null);resetMotion();refresh();});
$('.bz-motion').addEventListener('change',resetMotion);
canvas.addEventListener('pointerleave',()=>{if(!drag)resetMotion();});
if(motionMedia.addEventListener)motionMedia.addEventListener('change',resetMotion);
canvas.addEventListener('pointerdown',ev=>{ev.preventDefault();let p=point(ev),handle=(ev.shiftKey||$('.bz-multi').checked)?null:handleAt(p,bounds()),e=hit(p);resetMotion();if(!handle){if(!e){if(!ev.shiftKey&&!$('.bz-multi').checked)selectOne(null);refresh();return;}if(ev.shiftKey||$('.bz-multi').checked){if(selectedIds.has(e.id))selectedIds.delete(e.id);else selectedIds.add(e.id);selected=[...selectedIds].at(-1)||null;}else if(!selectedIds.has(e.id))selectOne(e.id);if(!selectedIds.size){refresh();return;}}save();drag={start:p,base:clone(bounds()),bases:clone(active()),handle:handle?.id};canvas.setPointerCapture(ev.pointerId);canvas.focus({preventScroll:true});refresh();});
canvas.addEventListener('pointermove',ev=>{let p=point(ev);if(!drag){if(!selected&&motionMedia.matches&&$('.bz-motion').checked){motion={x:Math.max(-1,Math.min(1,p.x/state.width*2-1)),y:Math.max(-1,Math.min(1,p.y/state.height*2-1))};$('.bz-stage').style.transform=`perspective(1200px) rotateX(${-motion.y*1.3}deg) rotateY(${motion.x*1.3}deg)`;paint();}let handle=handleAt(p,bounds());canvas.style.cursor=handle?(handle.id==='nw'||handle.id==='se'?'nwse-resize':'nesw-resize'):hit(p)?'move':'default';return;}let b=drag.base;guides=[];if(drag.handle){const west=drag.handle.includes('w'),north=drag.handle.includes('n'),ax=west?b.x+b.w:b.x,ay=north?b.y+b.h:b.y;let vx=(p.x-ax)*(west?-1:1),vy=(p.y-ay)*(north?-1:1),scale=Math.min(10,Math.max(.05,(vx*b.w+vy*b.h)/(b.w*b.w+b.h*b.h)));for(const base of drag.bases){let e=state.elements.find(x=>x.id===base.id);if(e.id==='product')e.h=Math.max(1,base.h*scale);else if(e.id==='background'){e.w=Math.max(1,base.w*scale);e.h=Math.max(1,base.h*scale);}else e.size=Math.max(8,base.size*scale);measure(e);e.x=ax+(base.x-ax)*scale;e.y=ay+(base.y-ay)*scale;}}else{let box={...b,x:b.x+p.x-drag.start.x,y:b.y+p.y-drag.start.y};if($('.bz-snap').checked){for(const axis of ['x','y']){let dim=axis==='x'?'w':'h',limit=axis==='x'?state.width:state.height,targets=[0,limit/2,limit,...state.elements.filter(t=>!selectedIds.has(t.id)).flatMap(t=>[t[axis],t[axis]+t[dim]/2,t[axis]+t[dim]])];let best=8*state.width/canvas.getBoundingClientRect().width,delta=0,line;for(const v of targets)for(const off of [0,box[dim]/2,box[dim]]){let d=v-box[axis]-off;if(Math.abs(d)<best){best=Math.abs(d);delta=d;line=v;}}box[axis]+=delta;if(line!==undefined)guides.push({axis,v:line});}}for(const base of drag.bases){let e=state.elements.find(x=>x.id===base.id);e.x=base.x+box.x-b.x;e.y=base.y+box.y-b.y;}}paint();});
const end=()=>{if(drag){drag=null;guides=[];refresh();}};canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('lostpointercapture',end);
canvas.addEventListener('keydown',ev=>{if(ev.key==='Escape'){selectOne(null);resetMotion();refresh();return;}if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='z'){ev.preventDefault();history(ev.shiftKey?'redo':'undo');return;}let e=current(),d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[ev.key];if(e&&d){ev.preventDefault();commit(()=>{moveSelection(d[0]*(ev.shiftKey?10:1),d[1]*(ev.shiftKey?10:1));});}});
$('.bz-text').addEventListener('focus',()=>{if(!$('.bz-text').dataset.editing){save();$('.bz-text').dataset.editing='1';}});$('.bz-text').addEventListener('input',ev=>{let e=current();e.text=ev.target.value;measure(e);fitToCanvas(e);remember();paint();});$('.bz-text').addEventListener('blur',()=>{delete $('.bz-text').dataset.editing;refresh();});
$('.bz-size').addEventListener('input',ev=>{if(!ev.target.dataset.editing){save();ev.target.dataset.editing='1';}let e=current();if(e.id==='product')e.h=+ev.target.value;else if(e.id==='background'){let ratio=e.w/Math.max(1,e.h);e.h=+ev.target.value;e.w=e.h*ratio;}else e.size=+ev.target.value;measure(e);fitToCanvas(e);remember();paint();});$('.bz-size').addEventListener('change',ev=>{delete ev.target.dataset.editing;refresh();});$('.bz-color').addEventListener('change',ev=>commit(()=>{active().filter(e=>e.id!=='product'&&e.id!=='background').forEach(e=>e.color=ev.target.value);}));
function history(a){let from=a==='undo'?undo:redo,to=a==='undo'?redo:undo;if(!from.length)return;to.push(clone(state));state=from.pop();refresh();}
root.addEventListener('click',async ev=>{let b=ev.target.closest('[data-action]');if(!b)return;let a=b.dataset.action,e=current();if(a==='clear'){selectOne(null);resetMotion();refresh();}if(a==='recover'&&e)commit(()=>{let b=bounds();moveSelection((state.width-b.w)/2-b.x,(state.height-b.h)/2-b.y);});if(a==='undo'||a==='redo')history(a);if(a==='reset')commit(()=>{state=clone(baseline);});if(a==='left'&&e)commit(()=>{let b=bounds();moveSelection(state.width*.07-b.x,0);});if(a==='right'&&e)commit(()=>{let b=bounds();moveSelection(state.width*.93-b.x-b.w,0);});if(a==='center'&&e)commit(()=>{let b=bounds();moveSelection((state.width-b.w)/2-b.x,0);});if(a==='middle'&&e)commit(()=>{let b=bounds();moveSelection(0,(state.height-b.h)/2-b.y);});if((a==='front'||a==='back')&&e)commit(()=>{let chosen=active(),rest=state.elements.filter(x=>!selectedIds.has(x.id));state.elements=a==='front'?[...rest,...chosen]:[...chosen,...rest];});if(a==='export'){b.disabled=true;try{await document.fonts.ready;await pic.decode();await bgpic.decode().catch(()=>{});let out=document.createElement('canvas');out.width=state.width;out.height=state.height;render(out.getContext('2d'),state,false);let blob=await new Promise(r=>out.toBlob(r,'image/png'));if(!blob)throw Error();let url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`BREEZ-${config.mode}-${config.variant}.png`;link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);$('.bz-status').textContent=`${state.width} × ${state.height}px PNG 저장 완료`;}catch(err){$('.bz-status').textContent='이미지를 저장하지 못했습니다. 다시 시도해주세요.';}finally{b.disabled=false;}}});
window.breezEditors[key]=async()=>{await document.fonts.ready;await pic.decode();await bgpic.decode();const out=document.createElement('canvas');out.width=state.width;out.height=state.height;render(out.getContext('2d'),state,false);const blob=await new Promise(r=>out.toBlob(r,'image/png'));if(!blob)throw Error('PNG 저장 실패');return blob;};
state=preset();fitAll(state);baseline=clone(state);let cached=window.breezEdits[key];if(cached){state=clone(cached.state);state.elements=cleanLegacyElements(state.elements,config.variant,state.width,state.height);undo=cleanLegacyHistory(cached.undo,config.variant,state.width,state.height);redo=cleanLegacyHistory(cached.redo,config.variant,state.width,state.height);if(selected&&isLocked(state.elements.find(e=>e.id===selected)))selectOne(null);}refresh();
const assetsReady=async()=>{await document.fonts.ready;const scan=document.createElement('canvas');scan.width=pic.naturalWidth;scan.height=pic.naturalHeight;const c=scan.getContext('2d',{willReadFrequently:true});c.drawImage(pic,0,0);let data=c.getImageData(0,0,scan.width,scan.height).data,x0=scan.width,y0=scan.height,x1=0,y1=0;for(let y=0;y<scan.height;y++)for(let x=0;x<scan.width;x++)if(data[(y*scan.width+x)*4+3]>12){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);}if(x1>=x0)crop={x:x0,y:y0,w:x1-x0+1,h:y1-y0+1};loaded=true;baseline=preset();fitAll(baseline);if(!cached&&!undo.length)state=clone(baseline);else{for(let e of state.elements){measure(e);fitToCanvas(e);}}refresh();};pic.onload=assetsReady;pic.onerror=()=>{$('.bz-status').textContent='제품 이미지를 불러오지 못했습니다.';};if(/^https?:/.test(src))pic.crossOrigin='anonymous';pic.src=src;
bgpic.onload=paint;bgpic.onerror=()=>{$('.bz-status').textContent='배경 이미지를 불러오지 못했습니다.';};bgpic.crossOrigin='anonymous';bgpic.src=window.breezBackgrounds[config.variant==='before'?'product':config.variant]||window.breezBackgrounds.product;
return ()=>{if(motionMedia.removeEventListener)motionMedia.removeEventListener('change',resetMotion);cancelAnimationFrame(raf);delete window.breezEditors[key];};
};

})();